### ISSUE TITLE
SIGPAC Downloader plugin crash

### ISSUE THREAD

**Issue by joseADA** [geomatico/qgis-sigpac#11]
My organization is having problems when using QGIS 3.14.15 (also 3.22).

The first issue comes when the plugin is installed. An error says "The plugin 'sigpac_downloader' could not be loaded because an error ocurred when calling the classFactory method" (translated from my spanish version of QGIS)

The full error trace is provided in the attached document "SIGPACDownloader_install.txt"

However there is apparently one workaround to that issue, you just have to select "reinstall" plugin and it finishes ok. After re-entering QGIS, the plugin is loaded and the menu entry appears in the "plugins" menu entry.

But the real problem comes when trying to use the plugin: The SIGPAC Downloader window opens and says you have to accept the Terms Of Use. When clicking on the proper button, a new window opens with blank content (nothing is loaded) and after a few seconds the QGIS "Unexpected Error" window appears suggesting to report the crash and quit the program. The crash report is enclosed in this email as "stack.txt"

Some relevant information about our QGIS settings: An HTTP Proxy is used for web connections, so the server, port, username and password are set in order to access the plugin repository.

Looking forward to hearing from you.
[SIGPACDownloader_install.txt](https://github.com/geomatico/qgis-sigpac/files/10083531/SIGPACDownloader_install.txt)
[stack.txt](https://github.com/geomatico/qgis-sigpac/files/10083532/stack.txt)

Kind Regards.

**Comment by mpericay** [comment]
Jose,
Thank you very much for using the SIGPAC Downloader and sending feedback. It seems that there has been some change in the FEGA ATOM services and the plugin has stopped working. We will try to fix it and post a new version soon, but we're depending on their external services.
